# Generated by Django 5.2.5 on 2025-08-31 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_education_user_education_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='internship',
            field=models.TextField(blank=True),
        ),
    ]
