# Generated by Django 5.2.5 on 2025-09-05 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_internship'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization_photo',
            field=models.ImageField(blank=True, null=True, upload_to='organization_photos/'),
        ),
    ]
