# Generated by Django 5.2.6 on 2025-10-08 14:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_auto_20250906_0706'),
        ('users', '0007_alter_user_official_name_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_token_reset',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='tokens_left',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='user',
            name='tokens_restored_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'job')},
            },
        ),
    ]
