# Generated by Django 5.2.6 on 2025-10-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_last_token_reset_user_tokens_left_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_token_reset',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
