# Generated by Django 5.2.6 on 2025-10-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_last_token_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hired_count',
            field=models.IntegerField(default=0, help_text='Total times hired'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_score',
            field=models.IntegerField(default=0, help_text='Calculated profile strength score'),
        ),
        migrations.AddField(
            model_name='user',
            name='selected_count',
            field=models.IntegerField(default=0, help_text='Total times selected for interview (regardless of final outcome)'),
        ),
        migrations.AddField(
            model_name='user',
            name='shortlisted_count',
            field=models.IntegerField(default=0, help_text='Total times shortlisted (regardless of final outcome)'),
        ),
    ]
