# Generated by Django 5.2.6 on 2025-11-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_is_kyc_verified_user_kyc_last_submitted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualkyc',
            name='current_step',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='individualkyc',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationkyc',
            name='current_step',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='organizationkyc',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
