# Generated by Django 5.2.6 on 2025-11-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_individualkyc_current_step_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualkyc',
            name='address_proof',
            field=models.FileField(blank=True, null=True, upload_to='kyc/individual/address/'),
        ),
        migrations.AddField(
            model_name='individualkyc',
            name='annual_income_range',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='individualkyc',
            name='citizenship_back',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/individual/citizenship/'),
        ),
        migrations.AddField(
            model_name='individualkyc',
            name='citizenship_front',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/individual/citizenship/'),
        ),
        migrations.AddField(
            model_name='individualkyc',
            name='citizenship_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individualkyc',
            name='citizenship_issue_district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='individualkyc',
            name='driving_license',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/individual/license/'),
        ),
        migrations.AddField(
            model_name='individualkyc',
            name='driving_license_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='individualkyc',
            name='education_level',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='individualkyc',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='individualkyc',
            name='expected_monthly_transaction',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='individualkyc',
            name='father_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='individualkyc',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='individualkyc',
            name='grandfather_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='individualkyc',
            name='is_fatca',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='individualkyc',
            name='is_pep',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='individualkyc',
            name='marital_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='individualkyc',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='individualkyc',
            name='mother_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='individualkyc',
            name='occupation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='individualkyc',
            name='passport_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='individualkyc',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/individual/passport/'),
        ),
        migrations.AddField(
            model_name='individualkyc',
            name='permanent_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='individualkyc',
            name='purpose_of_account',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='individualkyc',
            name='recent_photo',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/individual/photos/'),
        ),
        migrations.AddField(
            model_name='individualkyc',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='individualkyc',
            name='temporary_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='individualkyc',
            name='user_signature',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/individual/signatures/'),
        ),
        migrations.AddField(
            model_name='organizationkyc',
            name='authorized_person_declaration',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organizationkyc',
            name='board_resolution',
            field=models.FileField(blank=True, null=True, upload_to='kyc/organization/resolution/'),
        ),
        migrations.AddField(
            model_name='organizationkyc',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='organizationkyc',
            name='directors_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationkyc',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='organizationkyc',
            name='expected_monthly_transaction_volume',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='organizationkyc',
            name='industry_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='organizationkyc',
            name='is_fatca',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationkyc',
            name='is_pep',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationkyc',
            name='major_shareholders',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationkyc',
            name='moa_aa',
            field=models.FileField(blank=True, null=True, upload_to='kyc/organization/moa/'),
        ),
        migrations.AddField(
            model_name='organizationkyc',
            name='office_address_verification',
            field=models.FileField(blank=True, null=True, upload_to='kyc/organization/address/'),
        ),
        migrations.AddField(
            model_name='organizationkyc',
            name='operating_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organizationkyc',
            name='organization_stamp',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/organization/stamps/'),
        ),
        migrations.AddField(
            model_name='organizationkyc',
            name='organization_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='organizationkyc',
            name='pan_vat_certificate',
            field=models.FileField(blank=True, null=True, upload_to='kyc/organization/pan/'),
        ),
        migrations.AddField(
            model_name='organizationkyc',
            name='pan_vat_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='organizationkyc',
            name='partnership_agreement',
            field=models.FileField(blank=True, null=True, upload_to='kyc/organization/partnership/'),
        ),
        migrations.AddField(
            model_name='organizationkyc',
            name='registration_certificate',
            field=models.FileField(blank=True, null=True, upload_to='kyc/organization/registration/'),
        ),
        migrations.AddField(
            model_name='organizationkyc',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationkyc',
            name='signatory_citizenship',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/organization/signatory/'),
        ),
        migrations.AddField(
            model_name='organizationkyc',
            name='signatory_photo',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/organization/signatory/'),
        ),
        migrations.AddField(
            model_name='organizationkyc',
            name='source_of_funds',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='individualkyc',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='organizationkyc',
            name='org_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='organizationkyc',
            name='registered_address',
            field=models.TextField(blank=True),
        ),
    ]
