# Generated by Django 5.2.6 on 2025-11-16 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_individualkyc_address_proof_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('KYC_VERIFIED', 'KYC Verified'), ('KYC_REJECTED', 'KYC Rejected'), ('KYC_SUBMITTED', 'KYC Submitted'), ('KYC_MORE_INFO', 'KYC Request More Info'), ('JOB_APPLICATION', 'Job Application'), ('JOB_SHORTLIST', 'Job Shortlist'), ('JOB_OFFER', 'Job Offer'), ('GENERAL', 'General Notification')], default='GENERAL', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_id', models.IntegerField(blank=True, help_text='ID of related KYC/Job/Application', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='users_notif_user_id_c37f16_idx'), models.Index(fields=['user', 'is_read'], name='users_notif_user_id_1be17e_idx')],
            },
        ),
    ]
