# Generated by Django 5.2.4 on 2025-12-21 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Professional bio/summary'),
        ),
        migrations.AddField(
            model_name='user',
            name='employee_ranking',
            field=models.IntegerField(db_index=True, default=0, help_text='User ranking score based on profile completeness and achievements'),
        ),
        migrations.AddField(
            model_name='user',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('entry', 'Entry Level'), ('intermediate', 'Intermediate'), ('senior', 'Senior'), ('expert', 'Expert')], max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='industry_field',
            field=models.CharField(blank=True, help_text='Primary industry/field of expertise', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='organization_industry',
            field=models.CharField(blank=True, help_text="Organization's primary industry/field", max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_rating',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, help_text='User rating out of 5.0', max_digits=3),
        ),
        migrations.AddField(
            model_name='user',
            name='tagline',
            field=models.CharField(blank=True, help_text='Professional tagline or headline', max_length=200),
        ),
    ]
