# Generated by Django 5.2.4 on 2025-12-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_bio_user_employee_ranking_user_experience_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, help_text='URL to redirect when notification is clicked', max_length=500),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('KYC_VERIFIED', 'KYC Verified'), ('KYC_REJECTED', 'KYC Rejected'), ('KYC_SUBMITTED', 'KYC Submitted'), ('KYC_MORE_INFO', 'KYC Request More Info'), ('APP_SUBMITTED', 'Application Submitted'), ('APP_REVIEWED', 'Application Reviewed'), ('APP_SHORTLISTED', 'Application Shortlisted'), ('APP_SELECTED', 'Application Selected'), ('APP_HIRED', 'Application Hired'), ('APP_REJECTED', 'Application Rejected'), ('JOB_POSTED', 'Job Posted'), ('JOB_MATCHED', 'Job Matched'), ('NEW_APPLICATION', 'New Application Received'), ('INTEREST_RECEIVED', 'Interest Received'), ('PROFILE_VIEWED', 'Profile Viewed'), ('MESSAGE_RECEIVED', 'Message Received'), ('SYSTEM_ANNOUNCEMENT', 'System Announcement'), ('GENERAL', 'General Notification')], default='GENERAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_id',
            field=models.IntegerField(blank=True, help_text='ID of related object (KYC/Job/Application)', null=True),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='users_notif_notific_af6ddd_idx'),
        ),
    ]
