# Generated by Django 5.2.4 on 2025-12-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_update_notification_model'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='users_notif_notific_af6ddd_idx',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='link',
        ),
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, help_text='URL to redirect when notification is clicked', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_id',
            field=models.IntegerField(blank=True, help_text='ID of related KYC/Job/Application', null=True),
        ),
    ]
