# Generated by Django 5.2.6 on 2025-12-23 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_notification_users_notif_notific_af6ddd_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='official_name',
        ),
    ]
