# Generated by Django 5.2.4 on 2026-01-17 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_user_official_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_focus', models.CharField(help_text='Primary skills tested', max_length=255)),
                ('total_questions', models.IntegerField(default=10)),
                ('correct_answers', models.IntegerField(default=0)),
                ('wrong_answers', models.IntegerField(default=0)),
                ('total_time_seconds', models.IntegerField(help_text='Total time taken in seconds')),
                ('score', models.DecimalField(decimal_places=2, help_text='Final calculated score', max_digits=6)),
                ('questions_data', models.JSONField(help_text='JSON containing questions, answers, and user responses')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
