# Generated by Django 5.2.4 on 2025-09-06 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_job_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='organization/posters/'),
        ),
    ]
