# Generated by Django 5.2.4 on 2025-09-06 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_alter_job_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='poster',
        ),
    ]
