# Generated by Django 5.2.4 on 2025-09-06 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_remove_job_poster'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Organization', 'verbose_name_plural': 'Organization'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'Organization', 'verbose_name_plural': 'Organization'},
        ),
    ]
