# Generated by Django 5.2.4 on 2025-09-06 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_alter_application_options_alter_job_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Organization Application', 'verbose_name_plural': 'Organization Applications'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'Organization Job', 'verbose_name_plural': 'Organization Jobs'},
        ),
        migrations.AlterModelTable(
            name='application',
            table='organization_application',
        ),
        migrations.AlterModelTable(
            name='job',
            table='organization_job',
        ),
    ]
