# Generated by Django 5.2.4 on 2025-09-06 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_auto_20250906_0706'),
    ]

    operations = [
    ]
