# Generated by Django 5.2.6 on 2025-10-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_auto_20250906_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes from reviewers'),
        ),
        migrations.AddField(
            model_name='application',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('PD', 'Pending'), ('RV', 'Reviewing'), ('SL', 'Shortlisted'), ('SE', 'Selected'), ('RJ', 'Rejected'), ('HD', 'Hired')], default='PD', max_length=2),
        ),
    ]
