# Generated by Django 5.2.6 on 2025-10-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_application_notes_application_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('PD', 'Pending'), ('RV', 'Reviewing'), ('SL', 'Shortlisted'), ('SE', 'Selected'), ('RJ', 'Rejected'), ('WD', 'Withdrawn'), ('HD', 'Hired')], default='PD', max_length=2),
        ),
    ]
