# Generated by Django 5.2.4 on 2025-12-25 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_payment_premium_approved_at_payment_premium_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the follow relationship is active')),
                ('organization', models.ForeignKey(limit_choices_to={'user_type': 'ORG'}, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(limit_choices_to={'user_type': 'APP'}, on_delete=django.db.models.deletion.CASCADE, related_name='following_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-followed_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='organizatio_user_id_4e2950_idx'), models.Index(fields=['organization', 'is_active'], name='organizatio_organiz_8822b8_idx')],
                'unique_together': {('user', 'organization')},
            },
        ),
    ]
