# Generated by Django 5.2.4 on 2026-01-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0014_organizationfollow'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_type',
            field=models.CharField(choices=[('JOB', 'Job Application'), ('INT', 'Internship Application')], default='JOB', help_text='Type of application - automatically set based on job type', max_length=3),
        ),
    ]
