# Generated by Django 5.2.6 on 2025-09-06 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('git', models.CharField(max_length=100)),
                ('edu', models.CharField(max_length=100)),
                ('exp', models.CharField(max_length=100)),
                ('obj', models.CharField(max_length=200)),
                ('skills', models.CharField(max_length=200)),
                ('imge', models.ImageField(blank=True, default='photos/default.jpg', null=True, upload_to='')),
            ],
        ),
    ]
